# Generated by Django 3.0.4 on 2020-10-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bestseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Bookstore',
            fields=[
                ('bookstore_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('addr', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('tell_no', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bookstore/')),
            ],
        ),
        migrations.CreateModel(
            name='BookstoreTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'book_tag',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('bookstore_id', models.CharField(max_length=1000)),
                ('notice_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookstore_id', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('up_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
