# Generated by Django 3.0.4 on 2020-10-28 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sign', '0001_initial'),
        ('customer', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookstoretag',
            name='bookstore_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Bookstore'),
        ),
        migrations.AddField(
            model_name='bookstoretag',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sign.Tag'),
        ),
        migrations.AddField(
            model_name='bookstore',
            name='best_seller',
            field=models.ManyToManyField(through='manager.Bestseller', to='customer.Book'),
        ),
        migrations.AddField(
            model_name='bookstore',
            name='tag_id',
            field=models.ManyToManyField(through='manager.BookstoreTag', to='sign.Tag'),
        ),
        migrations.AddField(
            model_name='bestseller',
            name='book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Book'),
        ),
        migrations.AddField(
            model_name='bestseller',
            name='bookstore_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Bookstore'),
        ),
    ]
