# Generated by Django 3.0.6 on 2020-08-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('complain_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('complain', models.CharField(max_length=300)),
            ],
        ),
    ]
